// ==================== WORMHOLE TOPOLOGY ====================

export type Directions = {
  // Orthogonal directions
  N?: string | null;
  E?: string | null;
  S?: string | null;
  W?: string | null;
  in?: string | null;
  out?: string | null;
  cw?: string | null;
  ccw?: string | null;

  // Diagonal directions
  NE?: string | null;
  SE?: string | null;
  SW?: string | null;
  NW?: string | null;

  // for diagonals on wormhole layers (from the piece's perspective)
  idl?: string | null; // inner diagonal left
  idr?: string | null; // inner diagonal right
  od?: string | null; // outer diagonal
  odl?: string | null; // outer diagonal left
  odr?: string | null; // outer diagonal right
};

export const boardGraph: Record<string, Directions> = {
  a1: { N: "a2", E: "b1", S: null, W: null, NE: "b2" },
  a2: { N: "a3", E: "b2", S: "a1", W: null, NE: "b3", SE: "b1" },
  a3: { N: "a4", E: "b3", S: "a2", W: null, NE: "b4", SE: "b2" },
  a4: { N: "a5", E: "b4", S: "a3", W: null, NE: "b5", SE: "b3" },
  a5: { N: "a6", E: "b5", S: "a4", W: null, NE: "b6", SE: "b4" },
  a6: { N: "a7", E: "b6", S: "a5", W: null, NE: "b7", SE: "b5" },
  a7: { N: "a8", E: "b7", S: "a6", W: null, NE: "b8", SE: "b6" },
  a8: { N: null, E: "b8", S: "a7", W: null, SE: "b7" },

  b1: { N: "b2", E: "c1", S: null, W: "a1", NE: "c2", NW: "a2" },
  b2: {
    N: "b3",
    E: "c2",
    S: "b1",
    W: "a2",
    NE: "c3",
    SE: "c1",
    NW: "a3",
    SW: "a1",
  },
  b3: {
    N: "b4",
    E: "c3",
    S: "b2",
    W: "a3",
    NE: "c4",
    SE: "c2",
    NW: "a4",
    SW: "a2",
  },
  b4: {
    N: "b5",
    E: "c4",
    S: "b3",
    W: "a4",
    NE: "c5",
    SE: "c3",
    NW: "a5",
    SW: "a3",
  },
  b5: {
    N: "b6",
    E: "c5",
    S: "b4",
    W: "a5",
    NE: "c6",
    SE: "c4",
    NW: "a6",
    SW: "a4",
  },
  b6: {
    N: "b7",
    E: "c6",
    S: "b5",
    W: "a6",
    NE: "c7",
    SE: "c5",
    NW: "a7",
    SW: "a5",
  },
  b7: {
    N: "b8",
    E: "c7",
    S: "b6",
    W: "a7",
    NE: "c8",
    SE: "c6",
    NW: "a8",
    SW: "a6",
  },
  b8: {
    N: null,
    E: "c8",
    S: "b7",
    W: "a8",
    NE: null,
    SE: "c7",
    NW: null,
    SW: "a7",
  },

  c1: { N: "c2", E: "d1", S: null, W: "b1", NE: "d2", NW: "b2" },
  c2: {
    N: "c3",
    E: "d2",
    S: "c1",
    W: "b2",
    NE: "d3",
    SE: "d1",
    NW: "b3",
    SW: "b1",
  },
  c3: {
    N: "c4",
    E: "d3",
    S: "c2",
    W: "b3",
    in: "x1",
    cw: "c4",
    ccw: "d3",
    SW: "b2",
    NW: "b4",
    SE: "d2",
    idl: "x2",
    idr: "d4",
    odl: "d2",
    od: "b2",
    odr: "b4",
  },
  c4: {
    N: "c5",
    E: "x2",
    S: "c3",
    W: "b4",
    in: "x2",
    cw: "c5",
    ccw: "c3",
    SW: "b3",
    NW: "b5",
    NE: "x3",
    SE: "x1",
    idl: "x3",
    idr: "x1",
    odl: "b3",
    odr: "b5",
  },
  c5: {
    N: "c6",
    E: "x3",
    S: "c4",
    W: "b5",
    in: "x3",
    cw: "c6",
    ccw: "c4",
    SW: "b4",
    NW: "b6",
    NE: "x4",
    SE: "x2",
    idl: "x4",
    idr: "x2",
    odl: "b4",
    odr: "b6",
  },
  c6: {
    N: "c7",
    E: "d6",
    S: "c5",
    W: "b6",
    in: "x4",
    cw: "d6",
    ccw: "c5",
    SW: "b5",
    NW: "b7",
    NE: "d7",
    idl: "d5",
    idr: "x3",
    odl: "b5",
    od: "b7",
    odr: "d7",
  },
  c7: {
    N: "c8",
    E: "d7",
    S: "c6",
    W: "b7",
    NW: "b8",
    SW: "b6",
    NE: "d8",
    SE: "d6",
  },
  c8: { N: null, E: "d8", S: "c7", W: "b8", SW: "b7", SE: "d7" },

  x1: {
    out: "c3",
    cw: "x2",
    in: "x1'",
    ccw: "d4",
    idl: "x2'",
    idr: "d4'",
    odl: "d3",
    odr: "c4",
  },
  x2: {
    out: "c4",
    cw: "x3",
    in: "x2'",
    ccw: "x1",
    idl: "x3'",
    idr: "x1'",
    odl: "c3",
    odr: "c5",
  },
  x3: {
    out: "c5",
    cw: "x4",
    in: "x3'",
    ccw: "x2",
    idl: "x4'",
    idr: "x2'",
    odl: "c4",
    odr: "c6",
  },
  x4: {
    out: "c6",
    cw: "d5",
    in: "x4'",
    ccw: "x3",
    idl: "d5'",
    idr: "x3'",
    odl: "c5",
    odr: "d6",
  },

  d1: { N: "d2", E: "e1", S: null, W: "c1", NE: "e2", NW: "c2" },
  d2: {
    N: "d3",
    E: "e2",
    S: "d1",
    W: "c2",
    NE: "e3",
    SE: "e1",
    NW: "c3",
    SW: "c1",
  },
  d3: {
    N: "d4",
    E: "e3",
    S: "d2",
    W: "c3",
    in: "d4",
    out: "d2",
    cw: "c3",
    ccw: "e3",
    NE: "e4",
    SE: "e2",
    NW: "x1",
    SW: "c2",
    idl: "x1",
    idr: "e4",
    odl: "e2",
    odr: "c2",
  },
  d4: {
    N: "d4'",
    S: "d3",
    in: "d4'",
    out: "d3",
    cw: "x1",
    ccw: "e4",
    NE: "e4'",
    SE: "e3",
    NW: "x1'",
    SW: "c3",
    idl: "x1'",
    idr: "e4'",
    odl: "e3",
    odr: "c3",
  },
  d5: {
    N: "d6",
    S: "d5'",
    in: "d5'",
    out: "d6",
    cw: "e5",
    ccw: "x4",
    NE: "e6",
    SE: "e5'",
    NW: "c6",
    SW: "x4'",
    idl: "e5'",
    idr: "x4'",
    odl: "c6",
    odr: "e6",
  },
  d6: {
    N: "d7",
    E: "e6",
    S: "d5",
    W: "c6",
    in: "d5",
    out: "d7",
    cw: "e6",
    ccw: "c6",
    NE: "e7",
    SE: "e5",
    NW: "c7",
    SW: "x4",
    idl: "e5",
    idr: "x4",
    odl: "c7",
    odr: "e7",
  },
  d7: {
    N: "d8",
    E: "e7",
    S: "d6",
    W: "c7",
    NE: "e8",
    SE: "e6",
    NW: "c8",
    SW: "c6",
  },
  d8: { N: null, E: "e8", S: "d7", W: "c8", SW: "c7", SE: "e7" },

  e1: { N: "e2", E: "f1", S: null, W: "d1", NE: "f2", NW: "d2" },
  e2: {
    N: "e3",
    E: "f2",
    S: "e1",
    W: "d2",
    NE: "f3",
    SE: "f1",
    NW: "d3",
    SW: "d1",
  },
  e3: {
    N: "e4",
    E: "f3",
    S: "e2",
    W: "d3",
    in: "e4",
    out: "e2",
    cw: "d3",
    ccw: "f3",
    NW: "d4",
    NE: "y1",
    SE: "f2",
    SW: "d2",
    idl: "d4",
    idr: "y1",
    odl: "f2",
    odr: "d2",
  },
  e4: {
    N: "e4'",
    S: "e3",
    in: "e4'",
    out: "e3",
    cw: "d4",
    ccw: "y1",
    NE: "y1'",
    NW: "d4'",
    SE: "f3",
    SW: "d3",
    idl: "d4'",
    idr: "y1'",
    odl: "f3",
    odr: "d3",
  },
  e5: {
    N: "e6",
    S: "e5'",
    in: "e5'",
    out: "e6",
    cw: "y4",
    ccw: "d5",
    NE: "f6",
    SE: "y4'",
    NW: "d6",
    SW: "d5'",
    idl: "y4'",
    idr: "d5'",
    odl: "d6",
    odr: "f6",
  },
  e6: {
    N: "e7",
    E: "f6",
    S: "e5",
    W: "d6",
    in: "e5",
    out: "e7",
    cw: "f6",
    ccw: "d6",
    NE: "f7",
    SE: "y4",
    NW: "d7",
    SW: "d5",
    idl: "y4",
    idr: "d5",
    odl: "d7",
    odr: "f7",
  },
  e7: {
    N: "e8",
    E: "f7",
    S: "e6",
    W: "d7",
    NE: "f8",
    SE: "f6",
    NW: "d8",
    SW: "d6",
  },
  e8: { N: null, E: "f8", S: "e7", W: "d8", SW: "d7", SE: "f7" },

  y1: {
    in: "y1'",
    out: "f3",
    cw: "e4",
    ccw: "y2",
    idl: "e4'",
    idr: "y2'",
    odl: "f4",
    odr: "e3",
  },
  y2: {
    in: "y2'",
    out: "f4",
    cw: "y1",
    ccw: "y3",
    idl: "y1'",
    idr: "y3'",
    odl: "f5",
    odr: "f3",
  },
  y3: {
    in: "y3'",
    out: "f5",
    cw: "y2",
    ccw: "y4",
    idl: "y2'",
    idr: "y4'",
    odl: "f6",
    odr: "f4",
  },
  y4: {
    in: "y4'",
    out: "f6",
    cw: "y3",
    ccw: "e5",
    idl: "y3'",
    idr: "e5'",
    odl: "e6",
    odr: "f5",
  },

  f1: { N: "f2", E: "g1", S: null, W: "e1", NE: "g2", NW: "e2" },
  f2: {
    N: "f3",
    E: "g2",
    S: "f1",
    W: "e2",
    NE: "g3",
    SE: "g1",
    NW: "e3",
    SW: "e1",
  },
  f3: {
    N: "f4",
    E: "g3",
    S: "f2",
    W: "e3",
    in: "y1",
    cw: "e3",
    ccw: "f4",
    NE: "g4",
    SE: "g2",
    SW: "e2",
    idl: "e4",
    idr: "y2",
    odl: "g4",
    od: "g2",
    odr: "e2",
  },
  f4: {
    N: "f5",
    S: "f3",
    E: "g4",
    W: "y2",
    in: "y2",
    out: "g4",
    cw: "f3",
    ccw: "f5",
    NE: "g5",
    SE: "g3",
    SW: "y1",
    NW: "y3",
    idl: "y1",
    idr: "y3",
    odl: "g5",
    odr: "g3",
  },
  f5: {
    N: "f6",
    S: "f4",
    E: "g5",
    W: "y3",
    in: "y3",
    out: "g5",
    cw: "f4",
    ccw: "f6",
    NE: "g6",
    SE: "g4",
    SW: "y2",
    NW: "y4",
    idl: "y2",
    idr: "y4",
    odl: "g6",
    odr: "g4",
  },
  f6: {
    N: "f7",
    E: "g6",
    S: "f5",
    W: "e6",
    in: "y4",
    cw: "f5",
    ccw: "e6",
    NE: "g7",
    SE: "g5",
    SW: "y3",
    idl: "y3",
    idr: "e5",
    odl: "e7",
    od: "g7",
    odr: "g5",
  },
  f7: {
    N: "f8",
    E: "g7",
    S: "f6",
    W: "e7",
    NE: "g8",
    SE: "g6",
    NW: "e8",
    SW: "e6",
  },
  f8: { N: null, E: "g8", S: "f7", W: "e8", SW: "e7", SE: "g7" },

  g1: { N: "g2", E: "h1", S: null, W: "f1", NE: "h2", NW: "f2" },
  g2: {
    N: "g3",
    E: "h2",
    S: "g1",
    W: "f2",
    NE: "h3",
    SE: "h1",
    NW: "f3",
    SW: "f1",
  },
  g3: {
    N: "g4",
    E: "h3",
    S: "g2",
    W: "f3",
    NE: "h4",
    SE: "h2",
    NW: "f4",
    SW: "f2",
  },
  g4: {
    N: "g5",
    E: "h4",
    S: "g3",
    W: "f4",
    NE: "h5",
    SE: "h3",
    NW: "f5",
    SW: "f3",
  },
  g5: {
    N: "g6",
    E: "h5",
    S: "g4",
    W: "f5",
    NE: "h6",
    SE: "h4",
    NW: "f6",
    SW: "f4",
  },
  g6: {
    N: "g7",
    E: "h6",
    S: "g5",
    W: "f6",
    NE: "h7",
    SE: "h5",
    NW: "f7",
    SW: "f5",
  },
  g7: {
    N: "g8",
    E: "h7",
    S: "g6",
    W: "f7",
    NE: "h8",
    SE: "h6",
    NW: "f8",
    SW: "f6",
  },
  g8: { N: null, E: "h8", S: "g7", W: "f8", SW: "f7", SE: "h7" },

  h1: { N: "h2", E: null, S: null, W: "g1", NE: null, NW: "g2" },
  h2: {
    N: "h3",
    E: null,
    S: "h1",
    W: "g2",
    NE: null,
    SE: null,
    NW: "g3",
    SW: "g1",
  },
  h3: {
    N: "h4",
    E: null,
    S: "h2",
    W: "g3",
    NE: null,
    SE: null,
    NW: "g4",
    SW: "g2",
  },
  h4: {
    N: "h5",
    E: null,
    S: "h3",
    W: "g4",
    NE: null,
    SE: null,
    NW: "g5",
    SW: "g3",
  },
  h5: {
    N: "h6",
    E: null,
    S: "h4",
    W: "g5",
    NE: null,
    SE: null,
    NW: "g6",
    SW: "g4",
  },
  h6: {
    N: "h7",
    E: null,
    S: "h5",
    W: "g6",
    NE: null,
    SE: null,
    NW: "g7",
    SW: "g5",
  },
  h7: {
    N: "h8",
    E: null,
    S: "h6",
    W: "g7",
    NE: null,
    SE: null,
    NW: "g8",
    SW: "g6",
  },
  h8: { N: null, E: null, S: "h7", W: "g8", SW: "g7", SE: null },

  "a1'": { N: "a2'", E: "b1'", S: null, W: null, NE: "b2'" },
  "a2'": { N: "a3'", E: "b2'", S: "a1'", W: null, NE: "b3'", SE: "b1'" },
  "a3'": { N: "a4'", E: "b3'", S: "a2'", W: null, NE: "b4'", SE: "b2'" },
  "a4'": { N: "a5'", E: "b4'", S: "a3'", W: null, NE: "b5'", SE: "b3'" },
  "a5'": { N: "a6'", E: "b5'", S: "a4'", W: null, NE: "b6'", SE: "b4'" },
  "a6'": { N: "a7'", E: "b6'", S: "a5'", W: null, NE: "b7'", SE: "b5'" },
  "a7'": { N: "a8'", E: "b7'", S: "a6'", W: null, NE: "b8'", SE: "b6'" },
  "a8'": { N: null, E: "b8'", S: "a7'", W: null, SE: "b7'" },

  "b1'": { N: "b2'", E: "c1'", S: null, W: "a1'", NE: "c2'", NW: "a2'" },
  "b2'": {
    N: "b3'",
    E: "c2'",
    S: "b1'",
    W: "a2'",
    NE: "c3'",
    SE: "c1'",
    NW: "a3'",
    SW: "a1'",
  },
  "b3'": {
    N: "b4'",
    E: "c3'",
    S: "b2'",
    W: "a3'",
    NE: "c4'",
    SE: "c2'",
    NW: "a4'",
    SW: "a2'",
  },
  "b4'": {
    N: "b5'",
    E: "c4'",
    S: "b3'",
    W: "a4'",
    NE: "c5'",
    SE: "c3'",
    NW: "a5'",
    SW: "a3'",
  },
  "b5'": {
    N: "b6'",
    E: "c5'",
    S: "b4'",
    W: "a5'",
    NE: "c6'",
    SE: "c4'",
    NW: "a6'",
    SW: "a4'",
  },
  "b6'": {
    N: "b7'",
    E: "c6'",
    S: "b5'",
    W: "a6'",
    NE: "c7'",
    SE: "c5'",
    NW: "a7'",
    SW: "a5'",
  },
  "b7'": {
    N: "b8'",
    E: "c7'",
    S: "b6'",
    W: "a7'",
    NE: "c8'",
    SE: "c6'",
    NW: "a8'",
    SW: "a6'",
  },
  "b8'": {
    N: null,
    E: "c8'",
    S: "b7'",
    W: "a8'",
    SE: "c7'",
    NW: null,
    SW: "a7'",
  },

  "c1'": { N: "c2'", E: "d1'", S: null, W: "b1'", NE: "d2'", NW: "b2'" },
  "c2'": {
    N: "c3'",
    E: "d2'",
    S: "c1'",
    W: "b2'",
    NE: "d3'",
    SE: "d1'",
    NW: "b3'",
    SW: "b1'",
  },
  "c3'": {
    N: "c4'",
    E: "d3'",
    S: "c2'",
    W: "b3'",
    in: "x1'",
    cw: "c4'",
    ccw: "d3'",
    NW: "b4'",
    SW: "b2'",
    SE: "d2'",
    idl: "d4'",
    idr: "x2'",
    odl: "b4'",
    od: "b2'",
    odr: "d2'",
  },
  "c4'": {
    N: "c5'",
    E: "x2'",
    S: "c3'",
    W: "b4'",
    in: "x2'",
    cw: "c5'",
    ccw: "c3'",
    NW: "b5'",
    SW: "b3'",
    NE: "x3'",
    SE: "x1'",
    idl: "x1'",
    idr: "x3'",
    odl: "b5'",
    odr: "b3'",
  },
  "c5'": {
    N: "c6'",
    E: "x3'",
    S: "c4'",
    W: "b5'",
    in: "x3'",
    cw: "c6'",
    ccw: "c4'",
    NW: "b6'",
    SW: "b4'",
    NE: "x4'",
    SE: "x2'",
    idl: "x2'",
    idr: "x4'",
    odl: "b6'",
    odr: "b4'",
  },
  "c6'": {
    N: "c7'",
    E: "d6'",
    S: "c5'",
    W: "b6'",
    in: "x4'",
    cw: "d6'",
    ccw: "c5'",
    NE: "d7'",
    SW: "b5'",
    NW: "b7'",
    idl: "x3'",
    idr: "d5'",
    odl: "d7'",
    od: "b7'",
    odr: "b5'",
  },
  "c7'": {
    N: "c8'",
    E: "d7'",
    S: "c6'",
    W: "b7'",
    NE: "d8'",
    NW: "b8'",
    SW: "b6'",
    SE: "d6'",
  },
  "c8'": { N: null, E: "d8'", S: "c7'", W: "b8'", SW: "b7'", SE: "d7'" },

  "x1'": {
    out: "c3'",
    cw: "x2'",
    in: "x1",
    ccw: "d4'",
    idl: "d4",
    idr: "x2",
    odl: "c4'",
    odr: "d3'",
  },
  "x2'": {
    out: "c4'",
    cw: "x3'",
    in: "x2",
    ccw: "x1'",
    idl: "x1",
    idr: "x3",
    odl: "c5'",
    odr: "c3'",
  },
  "x3'": {
    out: "c5'",
    cw: "x4'",
    in: "x3",
    ccw: "x2'",
    idl: "x2",
    idr: "x4",
    odl: "c6'",
    odr: "c4'",
  },
  "x4'": {
    out: "c6'",
    cw: "d5'",
    in: "x4",
    ccw: "x3'",
    idl: "x3",
    idr: "d5",
    odl: "d5'",
    odr: "c5'",
  },

  "d1'": { N: "d2'", E: "e1'", S: null, W: "c1'", NE: "e2'", NW: "c2'" },
  "d2'": {
    N: "d3'",
    E: "e2'",
    S: "d1'",
    W: "c2'",
    NE: "e3'",
    SE: "e1'",
    NW: "c3'",
    SW: "c1'",
  },
  "d3'": {
    N: "d4'",
    E: "e3'",
    S: "d2'",
    W: "c3'",
    in: "d4'",
    out: "d2'",
    cw: "c3'",
    ccw: "e3'",
    NE: "e4'",
    SE: "e2'",
    NW: "x1'",
    SW: "c2'",
    idl: "e4'",
    idr: "x1'",
    odl: "c2'",
    odr: "e2'",
  },
  "d4'": {
    N: "d4",
    S: "d3'",
    in: "d4",
    out: "d3'",
    cw: "x1'",
    ccw: "e4'",
    NE: "e5",
    SE: "e3",
    NW: "x1",
    SW: "c3'",
    idl: "e5",
    idr: "x1",
    odl: "c3'",
    odr: "e3'",
  },
  "d5'": {
    N: "d6'",
    S: "d5",
    in: "d5",
    out: "d6'",
    cw: "e5'",
    ccw: "x4'",
    NE: "e6'",
    SE: "e5",
    NW: "c6'",
    SW: "x4",
    idl: "x4",
    idr: "e5",
    odl: "e6'",
    odr: "c6'",
  },
  "d6'": {
    N: "d7'",
    E: "e6'",
    S: "d5'",
    W: "c6'",
    in: "d5'",
    out: "d7'",
    cw: "e6'",
    ccw: "c6'",
    NE: "e7'",
    SE: "e5'",
    NW: "c7'",
    SW: "x4'",
    idl: "x4'",
    idr: "e5'",
    odl: "e7'",
    odr: "c7'",
  },
  "d7'": {
    N: "d8'",
    E: "e7'",
    S: "d6'",
    W: "c7'",
    NE: "e8'",
    SE: "e6'",
    NW: "c8'",
    SW: "c6'",
  },
  "d8'": { N: null, E: "e8'", S: "d7'", W: "c8'", SW: "c7'", SE: "e7'" },

  "e1'": { N: "e2'", E: "f1'", S: null, W: "d1'", NE: "f2'", NW: "d2'" },
  "e2'": {
    N: "e3'",
    E: "f2'",
    S: "e1'",
    W: "d2'",
    NE: "f3'",
    SE: "f1'",
    NW: "d3'",
    SW: "d1'",
  },
  "e3'": {
    N: "e4'",
    E: "f3'",
    S: "e2'",
    W: "d3'",
    in: "e4'",
    out: "e2'",
    cw: "d3'",
    ccw: "f3'",
    NE: "y1'",
    SE: "f2'",
    NW: "d4'",
    SW: "d2'",
    idl: "y1'",
    idr: "d4'",
    odl: "d2'",
    odr: "f2'",
  },
  "e4'": {
    N: "e4",
    S: "e3'",
    in: "e4",
    out: "e3'",
    cw: "d4'",
    ccw: "y1'",
    NE: "y1",
    NW: "d4",
    SE: "f3'",
    SW: "d3'",
    idl: "y1",
    idr: "d4",
    odl: "d3'",
    odr: "f3'",
  },
  "e5'": {
    N: "e6'",
    S: "e5",
    in: "e5",
    out: "e6'",
    cw: "y4'",
    ccw: "d5'",
    NE: "f6'",
    SE: "y4",
    NW: "d6'",
    SW: "d5",
    idl: "d5",
    idr: "y4",
    odl: "f6'",
    odr: "d6'",
  },
  "e6'": {
    N: "e7'",
    E: "f6'",
    S: "e5'",
    W: "d6'",
    in: "e5'",
    out: "e7'",
    cw: "f6'",
    ccw: "d6'",
    NE: "f7'",
    SE: "y4'",
    NW: "d7'",
    SW: "d5'",
    idl: "d5'",
    idr: "y4'",
    odl: "f7'",
    odr: "d7'",
  },
  "e7'": {
    N: "e8'",
    E: "f7'",
    S: "e6'",
    W: "d7'",
    NE: "f8'",
    SE: "f6'",
    NW: "d8'",
    SW: "d6'",
  },
  "e8'": { N: null, E: "f8'", S: "e7'", W: "d8'", SW: "d7'", SE: "f7'" },

  "y1'": {
    in: "y1",
    out: "f3'",
    cw: "e4'",
    ccw: "y2'",
    idl: "y2",
    idr: "e4",
    odl: "e3'",
    odr: "f4'",
  },
  "y2'": {
    in: "y2",
    out: "f4'",
    cw: "y1'",
    ccw: "y3'",
    idl: "y3",
    idr: "y1",
    odl: "f3'",
    odr: "f5'",
  },
  "y3'": {
    in: "y3",
    out: "f5'",
    cw: "y2'",
    ccw: "y4'",
    idl: "y4",
    idr: "y2",
    odl: "f4'",
    odr: "f6'",
  },
  "y4'": {
    in: "y4",
    out: "f6'",
    cw: "y3'",
    ccw: "e5'",
    idl: "e5",
    idr: "y3",
    odl: "f5'",
    odr: "e6'",
  },

  "f1'": { N: "f2'", E: "g1'", S: null, W: "e1'", NE: "g2'", NW: "e2'" },
  "f2'": {
    N: "f3'",
    E: "g2'",
    S: "f1'",
    W: "e2'",
    NE: "g3'",
    SE: "g1'",
    NW: "e3'",
    SW: "e1'",
  },
  "f3'": {
    N: "f4'",
    E: "g3'",
    S: "f2'",
    W: "e3'",
    in: "y1'",
    cw: "e3'",
    ccw: "f4'",
    NE: "g4'",
    SE: "g2'",
    SW: "e2'",
    idl: "y2'",
    idr: "e4'",
    odl: "e2'",
    od: "g2'",
    odr: "g4'",
  },
  "f4'": {
    N: "f5'",
    S: "f3'",
    E: "g4'",
    W: "y2'",
    in: "y2'",
    out: "g4'",
    cw: "f3'",
    ccw: "f5'",
    NE: "g5'",
    SE: "g3'",
    SW: "y1'",
    NW: "y3'",
    idl: "y3'",
    idr: "y1'",
    odl: "g3'",
    odr: "g5'",
  },
  "f5'": {
    N: "f6'",
    S: "f4'",
    E: "g5'",
    W: "y3'",
    in: "y3'",
    out: "g5'",
    cw: "f4'",
    ccw: "f6'",
    NE: "g6'",
    SE: "g4'",
    SW: "y2'",
    NW: "y4'",
    idl: "y4'",
    idr: "y2'",
    odl: "g4'",
    odr: "g6'",
  },
  "f6'": {
    N: "f7'",
    E: "g6'",
    S: "f5'",
    W: "e6'",
    in: "y4'",
    cw: "f5'",
    ccw: "e6'",
    NE: "g7'",
    SE: "g5'",
    NW: "e7'",
    idl: "e5'",
    idr: "y3'",
    odl: "g5'",
    od: "g7'",
    odr: "e7'",
  },
  "f7'": {
    N: "f8'",
    E: "g7'",
    S: "f'6",
    W: "e7'",
    NE: "g8'",
    SE: "g6'",
    NW: "e8'",
    SW: "e6'",
  },
  "f8'": { N: null, E: "g8'", S: "f7'", W: "e8'", SW: "e7'", SE: "g7'" },

  "g1'": { N: "g2'", E: "h1'", S: null, W: "f1'", NE: "h2'", NW: "f2'" },
  "g2'": {
    N: "g3'",
    E: "h2'",
    S: "g1'",
    W: "f2'",
    NE: "h3'",
    SE: "h1'",
    NW: "f3'",
    SW: "f1'",
  },
  "g3'": {
    N: "g4'",
    E: "h3'",
    S: "g2'",
    W: "f3'",
    NE: "h4'",
    SE: "h2'",
    NW: "f4'",
    SW: "f2'",
  },
  "g4'": {
    N: "g5'",
    E: "h4'",
    S: "g3'",
    W: "f4'",
    NE: "h5'",
    SE: "h3'",
    NW: "f5'",
    SW: "f3'",
  },
  "g5'": {
    N: "g6'",
    E: "h5'",
    S: "g4'",
    W: "f5'",
    NE: "h6'",
    SE: "h4'",
    NW: "f6'",
    SW: "f4'",
  },
  "g6'": {
    N: "g7'",
    E: "h6'",
    S: "g5'",
    W: "f6'",
    NE: "h7'",
    SE: "h5'",
    NW: "f7'",
    SW: "f5'",
  },
  "g7'": {
    N: "g8'",
    E: "h7'",
    S: "g6'",
    W: "f7'",
    NE: "h8'",
    SE: "h6'",
    NW: "f8'",
    SW: "f6'",
  },
  "g8'": { N: null, E: "h8'", S: "g7'", W: "f8'", SW: "f7'", SE: "h7'" },

  "h1'": { N: "h2'", E: null, S: null, W: "g1'", NE: null, NW: "g2'" },
  "h2'": {
    N: "h3'",
    E: null,
    S: "h1'",
    W: "g2'",
    NE: null,
    SE: null,
    NW: "g3'",
    SW: "g1'",
  },
  "h3'": {
    N: "h4'",
    E: null,
    S: "h2'",
    W: "g3'",
    NE: null,
    SE: null,
    NW: "g4'",
    SW: "g2'",
  },
  "h4'": {
    N: "h5'",
    E: null,
    S: "h3'",
    W: "g4'",
    NE: null,
    SE: null,
    NW: "g5'",
    SW: "g3'",
  },
  "h5'": {
    N: "h6'",
    E: null,
    S: "h4'",
    W: "g5'",
    NE: null,
    SE: null,
    NW: "g6'",
    SW: "g4'",
  },
  "h6'": {
    N: "h7'",
    E: null,
    S: "h5'",
    W: "g6'",
    NE: null,
    SE: null,
    NW: "g7'",
    SW: "g5'",
  },
  "h7'": {
    N: "h8'",
    E: null,
    S: "h6'",
    W: "g7'",
    NE: null,
    SE: null,
    NW: "g8'",
    SW: "g6'",
  },
  "h8'": { N: null, E: null, S: "h7'", W: "g8'", SW: "g7'", SE: null },
};